### ISSUE TITLE
Uncaught Typeerror 

### ISSUE THREAD

**Issue by Pursottam6003** [HamzaAnwar1998/ecommerce-site-with-react-hooks-and-firebase#1]
**Brother Increment decrement  is not working properly I had even copy pasted your code but its showing an error** 

IndividualCartProduct.js:10 Uncaught TypeError: cartProductIncrease is not a function
    at handleCartProductIncrease (IndividualCartProduct.js:10:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:1)
    at processDispatchQueue (react-dom.development.js:9086:1)
    at dispatchEventsForPlugins (react-dom.development.js:9097:1)
    at react-dom.development.js:9288:1

react-dom.development.js:4312 Uncaught TypeError: cartProductIncrease is not a function
    at handleCartProductIncrease (IndividualCartProduct.js:10:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:1)
    at processDispatchQueue (react-dom.development.js:9086:1)
    at dispatchEventsForPlugins (react-dom.development.js:9097:1)
    at react-dom.development.js:9288:1

**Comment by HamzaAnwar1998** [comment]
Hi @Pursottam6003

Everything is working for me. There are some suggestions you can try

1- Check your firebase version
2- Check if you have removed React.StrictMode in the index.js file

If you are still facing the same problem, I would suggest you add me as a collaborator on your GitHub repo or share your GitHub repo.
